<prodMod>
    text: "ENTER THE PRODUCTS"
    size_hint_y: None
    height: 70
    background_color: (0,0,0,1)
    canvas.before:
        Color:
            rgba: self.background_color
        Rectangle:
            size: self.size
            pos: self.pos

<scroll>
    ScrollView:
        do_scroll_y: True
        do_scroll_x: False    
        BoxLayout:
            orientation: "vertical"
            size_hint_y: None
            height: 1200
            id: prodContainer

<ProductSelection>
    Label:
        id: label1
        text: "-"
    Button: 
        id: button1
        varcont: "0"
        text: "ADD"
        on_press: root.onProdPress()

<KeyMod>
    text: "ENTER THE QUANTITY"
    size_hint_y: None
    height: 70

<KeyContainer>
    GridLayout:
        id: keyContainer
        cols: 3

<KeyPad>
    Button:
        id: button2
        text: "-"
        on_press: root.onKeyPress()

<ViewContainer>
    BoxLayout:
        id: viewContainer
        orientation: "vertical"

<ViewMod>
    text: "CURRENT PRODUCTS"

<ViewPad>
    orientation: "vertical"
    Button:
        id: button3
        text: "CLEAR"
        on_press: root.onClearPress()
    Button:
        id: button4
        text: "ENTER"
        on_press: root.onEnterPress()

<TestGrid>
    GridLayout:
        cols: 3
        size: root.width, root.height
        
        #PRODUCT SLICE
        BoxLayout:
            orientation: "vertical"
            id: prodGrid            

        BoxLayout:
            orientation: "vertical"
            id: keyGrid
            
        BoxLayout:
            orientation: "vertical"
            id: viewGrid
