<ProdMod>
    text: "ENTER THE PRODUCTS"
    size_hint_y: None
    height: 70
    background_color: (0,0,0,1)
    canvas.before:
        Color:
            rgba: self.background_color
        Rectangle:
            size: self.size
            pos: self.pos

<ProdScroll>
    ScrollView:
        do_scroll_y: True
        do_scroll_x: False    
        GridLayout:
            cols: 1
            size_hint: (1, None)
            height: self.minimum_height
            pos: self.pos
            id: prodContainer

<ProdSelection>
    size_hint_y: None
    height: 70
    Label:
        id: label1
        text: "-"
        text_size: self.width, None
        height: self.texture_size[1]
        halign: "center"
        markup: True
    Button: 
        id: button1
        varcont: "0"
        text: "ADD"
        on_press: root.onProdPress()

<KeyMod>
    text: "ENTER THE QUANTITY"
    size_hint_y: None
    height: 70

<KeyContainer>
    GridLayout:
        id: keyContainer
        cols: 3

<KeyPad>
    Button:
        id: button2
        text: "-"
        on_press: root.onKeyPress()

<ViewContainer>
    BoxLayout:
        id: viewContainer
        orientation: "vertical"

<ViewMod>
    text: "CURRENT PRODUCTS"
    size_hint_y: None
    height: 70

<ViewPad>
    orientation: "vertical"
    Button:
        id: button3
        text: "CLEAR"
        on_press: root.onClearPress()
    Button:
        id: button4
        text: "ENTER"
        on_press: root.onEnterPress()

<ViewScroll> 
    ScrollView:
        do_scroll_y: True
        do_scroll_x: False    
        GridLayout:
            cols: 1
            size_hint: (1, None)
            height: self.minimum_height
            pos: self.pos
            id: viewScrollContainer

<ViewSelection>
    size_hint_y: None
    height: 50
    GridLayout:
        cols: 4
        index: 0
        BoxLayout:
            orientation: "vertical"
            Label:
                text: "Picture" 
        BoxLayout: 
            orientation: "vertical"
            Label: 
                id: viewTitle
                text: "[b] LONG LONG PRODUCT TITLE [/b]"
                #size_hint_y: None
                text_size: self.width, None
                height: self.texture_size[1]
                halign: "center"
                markup: True
            Label: 
                id: viewQuantity
                halign: 'left'
                text: "Quantity"
                markup: True
        BoxLayout:
            orientation: "vertical"
            Label:
                id: viewPrice
                text: "[b] Price [/b]"
                markup: True
        BoxLayout:
            orientation: "vertical"
            Button:
                text: "Remove"
                on_press: root.removeItem()

#: import Factory kivy.factory.Factory
<StaffConfirmation@Popup>
    size_hint: 0.5, 0.8
    title_align: "center"
    id: staffTitle
    title: "Staff Select"
    BoxLayout:    
        orientation: "vertical"
        Label:
            size_hint_y: 0.2
            text: "Current Staff"
            id: currentStaff
        ScrollView:
            do_scroll_y: True
            do_scroll_x: False
            GridLayout:
                cols: 1
                size_hint: (1.0, None)
                height: self.minimum_height
                pos: self.pos
                id: staffContainer
        Label: 
            size_hint_y: 0.2
            text: "ADD STAFF"
        TextInput:
            id: textInput
            size_hint_y: 0.2
            on_focus: root.clearField()
        Button:
            size_hint_y: 0.4
            text: "Confirm"
            on_press: root.confirmStaff()
        Button:
            size_hint_y: 0.4
            text: "Cancel"
            on_press: root.dismiss()

<StaffError@Popup>
    autodismiss: False
    title_align: "center"
    size_hint: 0.2, 0.2
    title: "-"

<StaffConfirm@Popup>
    autodismiss: False
    title_align: "center"
    size_hint: 0.4, 0.2
    title: "Confirmation"
    first_popup: None
    GridLayout:
        cols: 2
        Button:
            text: "Cancel"
            on_press: root.dismiss()
        Button:
            text: "Confirm"
            on_press: root.setStaff()

<StaffPad>
    orientation: "vertical"
    Button:
        text: "DESELECT"
        on_press: root.selectStaff()
    Button:
        text: "ADD"
        on_press: root.confirmStaff()
    TextInput:
        id: textInput

<StaffSelection>
    size_hint_y: None
    height: 70
    BoxLayout:
        background_color: 0, 0, 0, 0
        canvas.before:
            Color:
                rgba: self.background_color
            Rectangle:
                pos: self.pos
                size: self.size
        Label: 
            id: staffTitle
            text: "-"
            text_size: self.width, None
            height: self.texture_size[1]
            markup: True
            halign: "center"
            valignL: "middle"
        Button:
            text: "Select"
            on_press: 
                root.updateStaff()
        

<TestGrid>
    BoxLayout:
        cols: 1
        orientation: "vertical"
        size: root.width, root.height
        GridLayout:
            cols: 2
            size_hint: 1, 0.1
            Button: 
                id: staffTitle
                background_color: 1, 1, 1, 1
                halign: "left"
                text: "Current Staff: None"
                on_press: root.activatePopup()
            Label:
                text: ""
        
        GridLayout:
            cols: 3
            BoxLayout:
                orientation: "vertical"
                id: prodGrid            

            BoxLayout:
                orientation: "vertical"
                id: keyGrid
                
            BoxLayout:
                orientation: "vertical"
                size_hint_x: 2
                id: viewGrid